### ISSUE TITLE
Exception : can not find input device with 8 channel(s)

### ISSUE THREAD

**Issue by cogmeta** [respeaker/mic_array_dfu#6]
Following exception while trying to run sudo python mic_array.py.

(0, 'bcm2835 ALSA: - (hw:0,0)', 0L, 2L)
(1, 'bcm2835 ALSA: IEC958/HDMI (hw:0,1)', 0L, 2L)
(2, 'seeed-4mic-voicecard: - (hw:1,0)', 2L, 0L)
(3, 'sysdefault', 0L, 128L)
(4, 'playback', 0L, 128L)
(5, 'dmixed', 0L, 2L)
(6, 'ac108', 4L, 0L)
(7, 'dmix', 0L, 2L)
(8, 'default', 4L, 128L)
Traceback (most recent call last):
  File "mic_array.py", line 190, in <module>
    test_8mic()
  File "mic_array.py", line 176, in test_8mic
    with MicArray(16000, 8, 16000 / 4)  as mic:
  File "mic_array.py", line 42, in __init__
    raise Exception('can not find input device with {} channel(s)'.format(self.channels))
Exception: can not find input device with 8 channel(s)

**Comment by cogmeta** [comment]
arecord -l
**** List of CAPTURE Hardware Devices ****
card 1: seeed4micvoicec [seeed-4mic-voicecard], device 0: bcm2835-i2s-ac108-codec0 ac108-codec0-0 []
  Subdevices: 1/1
  Subdevice #0: subdevice #0

**Comment by cogmeta** [comment]
sudo ./dfu --download respeaker_mic_array_8ch_raw.bin
VID = 0x2886, PID = 0x7, BCDDevice: 0x82
XMOS DFU application started - Interface 3 claimed
Detaching device from application mode.
Waiting for device to restart and enter DFU mode...
VID = 0x2886, PID = 0x7, BCDDevice: 0x82
... DFU firmware upgrade device opened
... Downloading image (respeaker_mic_array_8ch_raw.bin) to device
... Download complete
... Returning device to application mode

**Comment by cogmeta** [comment]
Do i need to remove card 1: seeed4micvoicec [seeed-4mic-voicecard]?

**Comment by cogmeta** [comment]
lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 9.1 (stretch)
Release:	9.1
Codename:	stretch

Raspberry pi model 3B

**Comment by cogmeta** [comment]
had to reinstall seeed-4mic-voicecard. Now it works !

**Comment by cogmeta** [comment]
had to reinstall seeed-4mic-voicecard. Now it works fine.
